### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bahmoudd**
- made some changes to the bootloader section
- some minor changes here and there

### CODE REVIEW

**Comment by XxAcielxX** [comment]
How is your experience with `SystemD-Boot`?

**Comment by Exvix** [comment]
It's a bit difficult to get up and running but the reward of integration with other SystemD programs and the very fast boot time makes it very worthwhile

**Comment by bahmoudd** [comment]
> How is your experience with `SystemD-Boot`?

It's a bit difficult to get up and running but the reward of integration with other SystemD programs and the very fast boot time makes it very worthwhile

**Comment by bahmoudd** [comment]
Also, I completely forgot to add the configuration instructions in time.

**Comment by XxAcielxX** [comment]
No problem, when you're fully done with this PR, let me know.

**Comment by Exvix** [comment]
Done.

**Comment by bahmoudd** [comment]
Done.

**Pull request merged**
